### ISSUE TITLE
hotFix: 지원자 페이지 owner undefined 에러 해결 및 건의사항 반영

### ISSUE THREAD

**Issue by hyosin-Jang** [Ludo-SMP/ludo-frontend#338]
### 실시간 알림

1. 알림 종모양 숫자 실시간 반영
   - 스터디 지원자 발생 시 실시간 알림 뜨고, 숫자 개수 실시간으로 변경되는 것 확인.

   <img width="600" alt="실시간 알림 숫자 변경" src="https://github.com/Ludo-SMP/ludo-frontend/assets/71035113/d6262e66-f86b-499a-90b9-8d0fa2a511da">
2.  전체 읽음 버튼 클릭 시 즉시 알림 목록 사라지도록 수정.
  - 쿼리캐시 read:false 갱신이 안되고 있었음.
  - `data.data.notificaiton[]` → `data.data[]`로 변경

### 스터디 지원자 페이지

1. `스터디원 모집` -> `스터디 지원자 확인하기`로 워딩 변경.

<img width="600" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/71035113/1f564b71-f8ef-479b-974e-eb179278bcda">

2. 스터디 바로 생성 후, 바로 지원자 페이지 접속 시, owner undefined 에러
  - 원인: 
     - `GET /studies/${studyId}/applicants` 에서 500 에러가 발생하고 있었는데 해당 API 응답값인 study, applicant에 접근하고 있었기 때문.

  - 해결:
      - 모집공고 미작성시, 지원자 확인하기 버튼이 안보이도록 처리. (***버튼 보이는 조건** : study.hasRecruitment && study.isOwner)
      - undefined check ?. 를 추가해서 undefined인 경우에도 property에 접근할 때 에러가 발생하지 않도록 수정.

API 500 에러 전문
```
{
  data: null,
  message: "Cannot invoke \"com.ludo.study.studymatchingplatform.study.domain.recruitment.Recruitment.getId()\" because. \"recruitment\" is null",
  ok: false
}
```

3. 제안: 
    - 내용: 
      - API response의 `ok`가 `true`일 경우에만 `data`에 접근하도록 변경
      - 공통 에러 핸들링 로직 추가
    - 이유: 
      - 현재는 API 요청이 `success`인지 `fail`인지 확인하지 않고 바로 `data`에 접근하고 있음.
      - fail일 경우 (ok: false) `data: null`이 내려오기 때문에 대부분의 `data`에 접근하는 로직들은 개별적으로 에러 핸들링이 필요함.
      - 따라서 개별 컴포넌트에서 data에 접근하기 전에 어플리케이션 공통 에러는 중앙 모듈`axios.interceptor.response` 나 `queryClient` 에서 핸들링하는 것이 어떨지 제안. (참고자료 확인)

### 모집공고 수정

1. 모집공고 수정 페이지 접속 시 map undefined 에러 해결 완료. 

  - [모집공고 상세 조회 API](https://docs.google.com/spreadsheets/d/1k5yFrSlqPm0CyEveOGeCBCnf-aVGZu66lDkS83l4K-A/edit?gid=0#gid=0&range=F11)에 출석일이 안내려오고 있었음.

  - 프론트 undefined 예외처리 및 API 응답 출석일 추가 문의 완료.

2. 모집공고 수정 API 500 에러 발생.

- URI: https://ludo.study/api/studies/97/recruitments

- Request Method: PUT

- Request payload
```
{
 applicantLimit: 4,
 callUrl: "www.naver.com",
 contact: "EMAIL",
 content: "운영체제 강의 듣고 내용 정리하고 발표하는 식 스터디\n\n예상 일정은 주 1~2회 정도 진행할 예정이고\n\n커리큘럼은 반효경 교수 님 수업 커리큘럼을 따르려고 합니다. \n\n같이 열심히 하실 분 모집합니다 !!",
 positionIds: [1, 4],
 recruitmentEndDateTime: "2024-07-11T00:00:00",
 stackIds: [12, 73],
 title: "운영체제 스터디 모집합니다. "
}
```
- Response
<img width="647" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/71035113/1c356cff-5759-40b3-b229-f29c4751b4a3">

3. 모집 공고 상세 내용에 줄바꿈이 적용되지 않는 이슈 해결 완료.

### 기타

- [x]  노션 배포된 링크로 변경.
- [x] `VitePluginRadar`로 GA, GTM 태그 심기

<br>

## 💡 참고자료
- [피그마 지원자 확인 페이지 ](https://www.figma.com/design/Sho4QHn0XqEptYBBlbf704/Page-Layout?node-id=4091-22029&t=Mh1ros1OTrv7uqhR-4)
- [axios.interceptor를 이용한 공통 에러 핸들링](https://velog.io/@krungy/axios-interceptors%EB%A5%BC-%ED%86%B5%ED%95%9C-API-%EA%B3%B5%ED%86%B5-%EC%82%AC%ED%95%AD-%EA%B4%80%EB%A6%AC)
- [React query 공통 에러 핸들링](https://9yujin.tistory.com/59)

**Comment by abiriadev** [comment]
@hyosin-Jang 
> GA 태그 심기. (WIP)

예전에 GA를 사용해 배포할때 다음 vite plugin으로 추가 코드 수정 없이 삽입했었습니다:
https://github.com/stafyniaksacha/vite-plugin-radar

코드 예시:
```ts
			VitePluginRadar({
				analytics: {
					id: env.GA_MEASUREMENT_ID,
				},
			}),
```

**Comment by abiriadev** [comment]
> * 모집공고 미작성시, 지원자 확인하기 버튼이 안보이도록 처리. (***버튼 보이는 조건** : !study.isRecruitment && study.isOwner)
> * undefined check ?. 를 추가해서 undefined인 경우에도 property에 접근할 때 에러가 발생하지 않도록 수정.

모집공고가 없을 시 모집공고 생성 링크가 포함된 빈 화면을 보여주는 것은 어떻게 생각하시나요?

예시:

![image](https://github.com/Ludo-SMP/ludo-frontend/assets/72962900/5b5f0960-ca60-4edb-a2ba-60a1293756fd)

**Comment by abiriadev** [comment]
아 사진을 보니 이미 작업하신 거군요

**Comment by hyosin-Jang** [comment]
@abiriadev 


> 예전에 GA를 사용해 배포할때 다음 vite plugin으로 추가 코드 수정 없이 삽입했었습니다: https://github.com/stafyniaksacha/vite-plugin-radar

오 vite plugin으로 GA를 설정할 수도 있군요. 적용해보겠습니다. 자료 감사해요.

**Comment by hyosin-Jang** [comment]
@abiriadev
> 모집공고가 없을 시 모집공고 생성 링크가 포함된 빈 화면을 보여주는 것은 어떻게 생각하시나요?

빈 화면은 불필요하게 depth가 깊어진다고 생각해서 모집공고 생성 시에만 버튼이 보이도록했는데
모집공고 작성페이지 진입점을 둔다면 사용자 입장에서 플로우가 자연스러울 것 같아요.

빠르게 반영해주셨네요 ㅎㅎ 감사합니다!
